### ISSUE TITLE
Update FsCheck post v1

### ISSUE THREAD

**Issue by haf** [mausch/Fuchu#36]

**Comment by mausch** [comment]
It seems there's a problem with the current FsCheck package, it requires .NET 4.5 even though I'm pretty sure it works on .NET 4.0 just fine. Gonna check this on the FsCheck repo.

**Comment by mausch** [comment]
It seems there's a problem with the current FsCheck package, it requires .NET 4.5 even though I'm pretty sure it works on .NET 4.0 just fine. Gonna check this on the FsCheck repo.

**Comment by mausch** [comment]
FsCheck requires v4.5 since 1.0.0 to use ExceptionDispatchInfo ( https://github.com/fsharp/FsCheck/commit/f248b094662b28b1c846f0e81e870129c10cbbda ).

Upgraded Fuchu projects that use FsCheck to v4.5 in 705b0f4edf431a56923c94224ee4e979e6b0b4bb  , then upgraded to FsCheck 1.0.4 in aed19cb673a99b1f19122d84b04fe86753a71051
