### ISSUE TITLE
Build broken when using `build.sh`

### ISSUE THREAD

**Issue by haf** [mausch/Fuchu#44]
OS X 10.10

``` bash
./build.sh: line 3: wget: command not found
mv: rename nuget.exe to ./.nuget/NuGet.exe: No such file or directory
chmod: ./.nuget/NuGet.exe: No such file or directory
Downloading FAKE...
Cannot open assembly './.nuget/NuGet.exe': No such file or directory.
Cannot open assembly 'packages/FAKE/tools/FAKE.exe': No such file or directory.
```

Recommend: curl.

**Comment by mausch** [comment]
No idea about OSX but I just [replaced wget with curl](https://github.com/mausch/Fuchu/commit/3afd10009c897485bf0dfce5638eb7a18b5e58c9) and [dockerized the build](https://github.com/mausch/Fuchu/commit/acdf19a3944ccee80821d8820357272c94dd947b) so it should build anywhere. AFAIK even on OSX with boot2docker since [mounting host volumes goes through a VirtualBox shared folder](https://github.com/boot2docker/boot2docker/pull/534).
